# Writes corpus_abi.hpp: a SHA-256 over the inputs that decide whether a
# compiled corpus fits this build (the runtime headers, the recompiler and the
# compile definitions), and the definitions themselves for the compiler.
string(REPLACE "|" ";" inputs "${INPUTS}")
string(REPLACE "|" ";" definitions "${DEFINITIONS}")
list(SORT inputs)
set(material "")
foreach(input IN LISTS inputs)
    get_filename_component(name "${input}" NAME)
    file(SHA256 "${input}" digest)
    string(APPEND material "${name}=${digest}\n")
endforeach()
set(flags "")
foreach(definition IN LISTS definitions)
    string(APPEND material "D${definition}\n")
    string(APPEND flags "\"-D${definition}\", ")
endforeach()
string(SHA256 abi "${material}")
set(content "// Generated by apps/portablekit/cmake/corpus_abi.cmake.
#pragma once
namespace portablekit::app {
inline constexpr const char *kCorpusAbi = \"${abi}\";
inline constexpr const char *kCorpusDefinitions[] = {${flags}nullptr};
}
")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if(previous STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${content}")
