#!/usr/bin/env python3
"""Compile the GE shaders to SPIR-V and emit them as C arrays.

    embed_shaders.py <glslang> <output.inc> <name=shader.glsl> ...

Keeping the SPIR-V in the binary means the renderer has no runtime file
dependency on the build directory.
"""

import os
import subprocess
import sys
import tempfile


def compile_shader(compiler, source):
    with tempfile.NamedTemporaryFile(suffix=".spv", delete=False) as handle:
        output = handle.name
    try:
        subprocess.run([compiler, "-V", source, "-o", output], check=True, capture_output=True)
        with open(output, "rb") as binary:
            return binary.read()
    finally:
        os.unlink(output)


def main(argv):
    if len(argv) < 4:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    compiler, destination = argv[1], argv[2]
    parts = []
    for entry in argv[3:]:
        name, _, path = entry.partition("=")
        data = compile_shader(compiler, path)
        words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
        body = ",\n    ".join(", ".join(f"0x{word:08x}u" for word in words[i:i + 6]) for i in range(0, len(words), 6))
        parts.append(f"// {os.path.basename(path)}, {len(data)} bytes\n"
                     f"constexpr std::uint32_t {name}[] = {{\n    {body},\n}};\n")
    os.makedirs(os.path.dirname(destination), exist_ok=True)
    with open(destination, "w") as out:
        out.write("// Generated by tools/embed_shaders.py. Do not edit.\n\n")
        out.write("\n".join(parts))
    print(f"embedded {len(parts)} shader(s) into {destination}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
