# Writes the header with the build version the in-game menu shows:
#   cmake -DSOURCE_DIR=<checkout> -DOUTPUT=<header> -P write_version.cmake
# The file is only rewritten when the version changes.
execute_process(
    COMMAND git describe --tags --always --dirty
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE describe
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR describe STREQUAL "")
    set(describe "unknown")
endif()
set(content "#pragma once\n\n// Generated by tools/write_version.cmake.\nnamespace portablekit {\ninline constexpr const char *kBuildVersion = \"${describe}\";\n}\n")
set(previous "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
